name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v4
      - run: npm ci
      - run: npm run lint

  build:
    name: 'Node ${{ matrix.node-version }}'

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: install dependencies
        run: npm ci
      - run: npm test

  release-git-compat:
    name: 'release-git@${{ matrix.release-git-version }}'

    runs-on: ubuntu-latest

    strategy:
      matrix:
        release-git-version: ['16.1.0']

    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v4
        with:
          node-version: 14
          cache: npm
      - name: install dependencies
        run: npm ci
      - run: npm install --saveDev release-git@${{ matrix.release-git-version }}
      - run: npm test
